package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1



/**
 * Administrateur generated by hbm2java
 */
public class Administrateur  implements java.io.Serializable {


     private AdministrateurId id;
     private Personne personne;
     private String supercode;

    public Administrateur() {
    }

	
    public Administrateur(AdministrateurId id, Personne personne) {
        this.id = id;
        this.personne = personne;
    }
    public Administrateur(AdministrateurId id, Personne personne, String supercode) {
       this.id = id;
       this.personne = personne;
       this.supercode = supercode;
    }
   
    public AdministrateurId getId() {
        return this.id;
    }
    
    public void setId(AdministrateurId id) {
        this.id = id;
    }
    public Personne getPersonne() {
        return this.personne;
    }
    
    public void setPersonne(Personne personne) {
        this.personne = personne;
    }
    public String getSupercode() {
        return this.supercode;
    }
    
    public void setSupercode(String supercode) {
        this.supercode = supercode;
    }




}


