package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Boutique generated by hbm2java
 */
public class Boutique  implements java.io.Serializable {


     private String codeboutique;
     private String nomboutique;
     private String adresse;
     private String email;
     private String telephone;
     private Set gerants = new HashSet(0);

    public Boutique() {
    }

	
    public Boutique(String codeboutique) {
        this.codeboutique = codeboutique;
    }
    public Boutique(String codeboutique, String nomboutique, String adresse, String email, String telephone, Set gerants) {
       this.codeboutique = codeboutique;
       this.nomboutique = nomboutique;
       this.adresse = adresse;
       this.email = email;
       this.telephone = telephone;
       this.gerants = gerants;
    }
   
    public String getCodeboutique() {
        return this.codeboutique;
    }
    
    public void setCodeboutique(String codeboutique) {
        this.codeboutique = codeboutique;
    }
    public String getNomboutique() {
        return this.nomboutique;
    }
    
    public void setNomboutique(String nomboutique) {
        this.nomboutique = nomboutique;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public Set getGerants() {
        return this.gerants;
    }
    
    public void setGerants(Set gerants) {
        this.gerants = gerants;
    }




}


