package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1



/**
 * CaissierId generated by hbm2java
 */
public class CaissierId  implements java.io.Serializable {


     private String idpersonne;
     private String type;
     private String codecaissier;

    public CaissierId() {
    }

    public CaissierId(String idpersonne, String type, String codecaissier) {
       this.idpersonne = idpersonne;
       this.type = type;
       this.codecaissier = codecaissier;
    }
   
    public String getIdpersonne() {
        return this.idpersonne;
    }
    
    public void setIdpersonne(String idpersonne) {
        this.idpersonne = idpersonne;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getCodecaissier() {
        return this.codecaissier;
    }
    
    public void setCodecaissier(String codecaissier) {
        this.codecaissier = codecaissier;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CaissierId) ) return false;
		 CaissierId castOther = ( CaissierId ) other; 
         
		 return ( (this.getIdpersonne()==castOther.getIdpersonne()) || ( this.getIdpersonne()!=null && castOther.getIdpersonne()!=null && this.getIdpersonne().equals(castOther.getIdpersonne()) ) )
 && ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
 && ( (this.getCodecaissier()==castOther.getCodecaissier()) || ( this.getCodecaissier()!=null && castOther.getCodecaissier()!=null && this.getCodecaissier().equals(castOther.getCodecaissier()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdpersonne() == null ? 0 : this.getIdpersonne().hashCode() );
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         result = 37 * result + ( getCodecaissier() == null ? 0 : this.getCodecaissier().hashCode() );
         return result;
   }   


}


