package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Caissier generated by hbm2java
 */
public class Caissier  implements java.io.Serializable {


     private CaissierId id;
     private Employe employe;
     private Set ecaissements = new HashSet(0);

    public Caissier() {
    }

	
    public Caissier(CaissierId id, Employe employe) {
        this.id = id;
        this.employe = employe;
    }
    public Caissier(CaissierId id, Employe employe, Set ecaissements) {
       this.id = id;
       this.employe = employe;
       this.ecaissements = ecaissements;
    }
   
    public CaissierId getId() {
        return this.id;
    }
    
    public void setId(CaissierId id) {
        this.id = id;
    }
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }
    public Set getEcaissements() {
        return this.ecaissements;
    }
    
    public void setEcaissements(Set ecaissements) {
        this.ecaissements = ecaissements;
    }




}


