package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1



/**
 * CalendrierserviceId generated by hbm2java
 */
public class CalendrierserviceId  implements java.io.Serializable {


     private String idpersonne;
     private String type;
     private String codejour;
     private String heurefin;

    public CalendrierserviceId() {
    }

    public CalendrierserviceId(String idpersonne, String type, String codejour, String heurefin) {
       this.idpersonne = idpersonne;
       this.type = type;
       this.codejour = codejour;
       this.heurefin = heurefin;
    }
   
    public String getIdpersonne() {
        return this.idpersonne;
    }
    
    public void setIdpersonne(String idpersonne) {
        this.idpersonne = idpersonne;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getCodejour() {
        return this.codejour;
    }
    
    public void setCodejour(String codejour) {
        this.codejour = codejour;
    }
    public String getHeurefin() {
        return this.heurefin;
    }
    
    public void setHeurefin(String heurefin) {
        this.heurefin = heurefin;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CalendrierserviceId) ) return false;
		 CalendrierserviceId castOther = ( CalendrierserviceId ) other; 
         
		 return ( (this.getIdpersonne()==castOther.getIdpersonne()) || ( this.getIdpersonne()!=null && castOther.getIdpersonne()!=null && this.getIdpersonne().equals(castOther.getIdpersonne()) ) )
 && ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
 && ( (this.getCodejour()==castOther.getCodejour()) || ( this.getCodejour()!=null && castOther.getCodejour()!=null && this.getCodejour().equals(castOther.getCodejour()) ) )
 && ( (this.getHeurefin()==castOther.getHeurefin()) || ( this.getHeurefin()!=null && castOther.getHeurefin()!=null && this.getHeurefin().equals(castOther.getHeurefin()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdpersonne() == null ? 0 : this.getIdpersonne().hashCode() );
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         result = 37 * result + ( getCodejour() == null ? 0 : this.getCodejour().hashCode() );
         result = 37 * result + ( getHeurefin() == null ? 0 : this.getHeurefin().hashCode() );
         return result;
   }   


}


