package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1



/**
 * Calendrierservice generated by hbm2java
 */
public class Calendrierservice  implements java.io.Serializable {


     private CalendrierserviceId id;
     private Employe employe;
     private Jour jour;
     private String heuredebut;
     private String datepriseservice;

    public Calendrierservice() {
    }

	
    public Calendrierservice(CalendrierserviceId id, Employe employe, Jour jour) {
        this.id = id;
        this.employe = employe;
        this.jour = jour;
    }
    public Calendrierservice(CalendrierserviceId id, Employe employe, Jour jour, String heuredebut, String datepriseservice) {
       this.id = id;
       this.employe = employe;
       this.jour = jour;
       this.heuredebut = heuredebut;
       this.datepriseservice = datepriseservice;
    }
   
    public CalendrierserviceId getId() {
        return this.id;
    }
    
    public void setId(CalendrierserviceId id) {
        this.id = id;
    }
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }
    public Jour getJour() {
        return this.jour;
    }
    
    public void setJour(Jour jour) {
        this.jour = jour;
    }
    public String getHeuredebut() {
        return this.heuredebut;
    }
    
    public void setHeuredebut(String heuredebut) {
        this.heuredebut = heuredebut;
    }
    public String getDatepriseservice() {
        return this.datepriseservice;
    }
    
    public void setDatepriseservice(String datepriseservice) {
        this.datepriseservice = datepriseservice;
    }




}


