package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private ClientId id;
     private Personne personne;
     private String categorie;
     private String vip;
     private Integer label;
     private Set paniers = new HashSet(0);

    public Client() {
    }

	
    public Client(ClientId id, Personne personne) {
        this.id = id;
        this.personne = personne;
    }
    public Client(ClientId id, Personne personne, String categorie, String vip, Integer label, Set paniers) {
       this.id = id;
       this.personne = personne;
       this.categorie = categorie;
       this.vip = vip;
       this.label = label;
       this.paniers = paniers;
    }
   
    public ClientId getId() {
        return this.id;
    }
    
    public void setId(ClientId id) {
        this.id = id;
    }
    public Personne getPersonne() {
        return this.personne;
    }
    
    public void setPersonne(Personne personne) {
        this.personne = personne;
    }
    public String getCategorie() {
        return this.categorie;
    }
    
    public void setCategorie(String categorie) {
        this.categorie = categorie;
    }
    public String getVip() {
        return this.vip;
    }
    
    public void setVip(String vip) {
        this.vip = vip;
    }
    public Integer getLabel() {
        return this.label;
    }
    
    public void setLabel(Integer label) {
        this.label = label;
    }
    public Set getPaniers() {
        return this.paniers;
    }
    
    public void setPaniers(Set paniers) {
        this.paniers = paniers;
    }




}


