package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Commandeclient generated by hbm2java
 */
public class Commandeclient  implements java.io.Serializable {


     private String codecom;
     private Livraison livraison;
     private Panier panier;
     private String datecom;
     private String etatlivraison;
     private Set factureclients = new HashSet(0);

    public Commandeclient() {
    }

	
    public Commandeclient(String codecom) {
        this.codecom = codecom;
    }
    public Commandeclient(String codecom, Livraison livraison, Panier panier, String datecom, String etatlivraison, Set factureclients) {
       this.codecom = codecom;
       this.livraison = livraison;
       this.panier = panier;
       this.datecom = datecom;
       this.etatlivraison = etatlivraison;
       this.factureclients = factureclients;
    }
   
    public String getCodecom() {
        return this.codecom;
    }
    
    public void setCodecom(String codecom) {
        this.codecom = codecom;
    }
    public Livraison getLivraison() {
        return this.livraison;
    }
    
    public void setLivraison(Livraison livraison) {
        this.livraison = livraison;
    }
    public Panier getPanier() {
        return this.panier;
    }
    
    public void setPanier(Panier panier) {
        this.panier = panier;
    }
    public String getDatecom() {
        return this.datecom;
    }
    
    public void setDatecom(String datecom) {
        this.datecom = datecom;
    }
    public String getEtatlivraison() {
        return this.etatlivraison;
    }
    
    public void setEtatlivraison(String etatlivraison) {
        this.etatlivraison = etatlivraison;
    }
    public Set getFactureclients() {
        return this.factureclients;
    }
    
    public void setFactureclients(Set factureclients) {
        this.factureclients = factureclients;
    }




}


