package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1



/**
 * Conditionnement generated by hbm2java
 */
public class Conditionnement  implements java.io.Serializable {


     private String codecondi;
     private Produit produit;
     private String libelle;

    public Conditionnement() {
    }

	
    public Conditionnement(String codecondi) {
        this.codecondi = codecondi;
    }
    public Conditionnement(String codecondi, Produit produit, String libelle) {
       this.codecondi = codecondi;
       this.produit = produit;
       this.libelle = libelle;
    }
   
    public String getCodecondi() {
        return this.codecondi;
    }
    
    public void setCodecondi(String codecondi) {
        this.codecondi = codecondi;
    }
    public Produit getProduit() {
        return this.produit;
    }
    
    public void setProduit(Produit produit) {
        this.produit = produit;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }




}


