package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1



/**
 * Detailsmessage generated by hbm2java
 */
public class Detailsmessage  implements java.io.Serializable {


     private DetailsmessageId id;
     private Message message;
     private Personne personne;
     private String emetteur;
     private String recepteur;
     private String dateenvoi;
     private String datereception;

    public Detailsmessage() {
    }

	
    public Detailsmessage(DetailsmessageId id, Message message, Personne personne) {
        this.id = id;
        this.message = message;
        this.personne = personne;
    }
    public Detailsmessage(DetailsmessageId id, Message message, Personne personne, String emetteur, String recepteur, String dateenvoi, String datereception) {
       this.id = id;
       this.message = message;
       this.personne = personne;
       this.emetteur = emetteur;
       this.recepteur = recepteur;
       this.dateenvoi = dateenvoi;
       this.datereception = datereception;
    }
   
    public DetailsmessageId getId() {
        return this.id;
    }
    
    public void setId(DetailsmessageId id) {
        this.id = id;
    }
    public Message getMessage() {
        return this.message;
    }
    
    public void setMessage(Message message) {
        this.message = message;
    }
    public Personne getPersonne() {
        return this.personne;
    }
    
    public void setPersonne(Personne personne) {
        this.personne = personne;
    }
    public String getEmetteur() {
        return this.emetteur;
    }
    
    public void setEmetteur(String emetteur) {
        this.emetteur = emetteur;
    }
    public String getRecepteur() {
        return this.recepteur;
    }
    
    public void setRecepteur(String recepteur) {
        this.recepteur = recepteur;
    }
    public String getDateenvoi() {
        return this.dateenvoi;
    }
    
    public void setDateenvoi(String dateenvoi) {
        this.dateenvoi = dateenvoi;
    }
    public String getDatereception() {
        return this.datereception;
    }
    
    public void setDatereception(String datereception) {
        this.datereception = datereception;
    }




}


