package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1



/**
 * Factureclient generated by hbm2java
 */
public class Factureclient  implements java.io.Serializable {


     private String codefact;
     private Commandeclient commandeclient;
     private String datefact;
     private Integer montantfact;

    public Factureclient() {
    }

	
    public Factureclient(String codefact) {
        this.codefact = codefact;
    }
    public Factureclient(String codefact, Commandeclient commandeclient, String datefact, Integer montantfact) {
       this.codefact = codefact;
       this.commandeclient = commandeclient;
       this.datefact = datefact;
       this.montantfact = montantfact;
    }
   
    public String getCodefact() {
        return this.codefact;
    }
    
    public void setCodefact(String codefact) {
        this.codefact = codefact;
    }
    public Commandeclient getCommandeclient() {
        return this.commandeclient;
    }
    
    public void setCommandeclient(Commandeclient commandeclient) {
        this.commandeclient = commandeclient;
    }
    public String getDatefact() {
        return this.datefact;
    }
    
    public void setDatefact(String datefact) {
        this.datefact = datefact;
    }
    public Integer getMontantfact() {
        return this.montantfact;
    }
    
    public void setMontantfact(Integer montantfact) {
        this.montantfact = montantfact;
    }




}


