package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fournisseur generated by hbm2java
 */
public class Fournisseur  implements java.io.Serializable {


     private FournisseurId id;
     private Facturefournisseur facturefournisseur;
     private Personne personne;
     private String securefour;
     private Integer compteur;
     private Set lignedevises = new HashSet(0);
     private Set commandestocks = new HashSet(0);

    public Fournisseur() {
    }

	
    public Fournisseur(FournisseurId id, Personne personne) {
        this.id = id;
        this.personne = personne;
    }
    public Fournisseur(FournisseurId id, Facturefournisseur facturefournisseur, Personne personne, String securefour, Integer compteur, Set lignedevises, Set commandestocks) {
       this.id = id;
       this.facturefournisseur = facturefournisseur;
       this.personne = personne;
       this.securefour = securefour;
       this.compteur = compteur;
       this.lignedevises = lignedevises;
       this.commandestocks = commandestocks;
    }
   
    public FournisseurId getId() {
        return this.id;
    }
    
    public void setId(FournisseurId id) {
        this.id = id;
    }
    public Facturefournisseur getFacturefournisseur() {
        return this.facturefournisseur;
    }
    
    public void setFacturefournisseur(Facturefournisseur facturefournisseur) {
        this.facturefournisseur = facturefournisseur;
    }
    public Personne getPersonne() {
        return this.personne;
    }
    
    public void setPersonne(Personne personne) {
        this.personne = personne;
    }
    public String getSecurefour() {
        return this.securefour;
    }
    
    public void setSecurefour(String securefour) {
        this.securefour = securefour;
    }
    public Integer getCompteur() {
        return this.compteur;
    }
    
    public void setCompteur(Integer compteur) {
        this.compteur = compteur;
    }
    public Set getLignedevises() {
        return this.lignedevises;
    }
    
    public void setLignedevises(Set lignedevises) {
        this.lignedevises = lignedevises;
    }
    public Set getCommandestocks() {
        return this.commandestocks;
    }
    
    public void setCommandestocks(Set commandestocks) {
        this.commandestocks = commandestocks;
    }




}


