package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1



/**
 * FournisseurId generated by hbm2java
 */
public class FournisseurId  implements java.io.Serializable {


     private String idpersonne;
     private String codefour;

    public FournisseurId() {
    }

    public FournisseurId(String idpersonne, String codefour) {
       this.idpersonne = idpersonne;
       this.codefour = codefour;
    }
   
    public String getIdpersonne() {
        return this.idpersonne;
    }
    
    public void setIdpersonne(String idpersonne) {
        this.idpersonne = idpersonne;
    }
    public String getCodefour() {
        return this.codefour;
    }
    
    public void setCodefour(String codefour) {
        this.codefour = codefour;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FournisseurId) ) return false;
		 FournisseurId castOther = ( FournisseurId ) other; 
         
		 return ( (this.getIdpersonne()==castOther.getIdpersonne()) || ( this.getIdpersonne()!=null && castOther.getIdpersonne()!=null && this.getIdpersonne().equals(castOther.getIdpersonne()) ) )
 && ( (this.getCodefour()==castOther.getCodefour()) || ( this.getCodefour()!=null && castOther.getCodefour()!=null && this.getCodefour().equals(castOther.getCodefour()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdpersonne() == null ? 0 : this.getIdpersonne().hashCode() );
         result = 37 * result + ( getCodefour() == null ? 0 : this.getCodefour().hashCode() );
         return result;
   }   


}


