package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1



/**
 * GerantId generated by hbm2java
 */
public class GerantId  implements java.io.Serializable {


     private String idpersonne;
     private String type;
     private String codegerant;

    public GerantId() {
    }

    public GerantId(String idpersonne, String type, String codegerant) {
       this.idpersonne = idpersonne;
       this.type = type;
       this.codegerant = codegerant;
    }
   
    public String getIdpersonne() {
        return this.idpersonne;
    }
    
    public void setIdpersonne(String idpersonne) {
        this.idpersonne = idpersonne;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getCodegerant() {
        return this.codegerant;
    }
    
    public void setCodegerant(String codegerant) {
        this.codegerant = codegerant;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GerantId) ) return false;
		 GerantId castOther = ( GerantId ) other; 
         
		 return ( (this.getIdpersonne()==castOther.getIdpersonne()) || ( this.getIdpersonne()!=null && castOther.getIdpersonne()!=null && this.getIdpersonne().equals(castOther.getIdpersonne()) ) )
 && ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
 && ( (this.getCodegerant()==castOther.getCodegerant()) || ( this.getCodegerant()!=null && castOther.getCodegerant()!=null && this.getCodegerant().equals(castOther.getCodegerant()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdpersonne() == null ? 0 : this.getIdpersonne().hashCode() );
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         result = 37 * result + ( getCodegerant() == null ? 0 : this.getCodegerant().hashCode() );
         return result;
   }   


}


