package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Jour generated by hbm2java
 */
public class Jour  implements java.io.Serializable {


     private String codejour;
     private String libelle;
     private Set calendrierservices = new HashSet(0);

    public Jour() {
    }

	
    public Jour(String codejour) {
        this.codejour = codejour;
    }
    public Jour(String codejour, String libelle, Set calendrierservices) {
       this.codejour = codejour;
       this.libelle = libelle;
       this.calendrierservices = calendrierservices;
    }
   
    public String getCodejour() {
        return this.codejour;
    }
    
    public void setCodejour(String codejour) {
        this.codejour = codejour;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
    public Set getCalendrierservices() {
        return this.calendrierservices;
    }
    
    public void setCalendrierservices(Set calendrierservices) {
        this.calendrierservices = calendrierservices;
    }




}


