package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1



/**
 * LignecommandepanierId generated by hbm2java
 */
public class LignecommandepanierId  implements java.io.Serializable {


     private String codepanier;
     private String codeprod;
     private String format;
     private String designation;

    public LignecommandepanierId() {
    }

    public LignecommandepanierId(String codepanier, String codeprod, String format, String designation) {
       this.codepanier = codepanier;
       this.codeprod = codeprod;
       this.format = format;
       this.designation = designation;
    }
   
    public String getCodepanier() {
        return this.codepanier;
    }
    
    public void setCodepanier(String codepanier) {
        this.codepanier = codepanier;
    }
    public String getCodeprod() {
        return this.codeprod;
    }
    
    public void setCodeprod(String codeprod) {
        this.codeprod = codeprod;
    }
    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LignecommandepanierId) ) return false;
		 LignecommandepanierId castOther = ( LignecommandepanierId ) other; 
         
		 return ( (this.getCodepanier()==castOther.getCodepanier()) || ( this.getCodepanier()!=null && castOther.getCodepanier()!=null && this.getCodepanier().equals(castOther.getCodepanier()) ) )
 && ( (this.getCodeprod()==castOther.getCodeprod()) || ( this.getCodeprod()!=null && castOther.getCodeprod()!=null && this.getCodeprod().equals(castOther.getCodeprod()) ) )
 && ( (this.getFormat()==castOther.getFormat()) || ( this.getFormat()!=null && castOther.getFormat()!=null && this.getFormat().equals(castOther.getFormat()) ) )
 && ( (this.getDesignation()==castOther.getDesignation()) || ( this.getDesignation()!=null && castOther.getDesignation()!=null && this.getDesignation().equals(castOther.getDesignation()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodepanier() == null ? 0 : this.getCodepanier().hashCode() );
         result = 37 * result + ( getCodeprod() == null ? 0 : this.getCodeprod().hashCode() );
         result = 37 * result + ( getFormat() == null ? 0 : this.getFormat().hashCode() );
         result = 37 * result + ( getDesignation() == null ? 0 : this.getDesignation().hashCode() );
         return result;
   }   


}


