package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1



/**
 * Lignecommandepanier generated by hbm2java
 */
public class Lignecommandepanier  implements java.io.Serializable {


     private LignecommandepanierId id;
     private Panier panier;
     private Produit produit;
     private Integer quantite;

    public Lignecommandepanier() {
    }

	
    public Lignecommandepanier(LignecommandepanierId id, Panier panier, Produit produit) {
        this.id = id;
        this.panier = panier;
        this.produit = produit;
    }
    public Lignecommandepanier(LignecommandepanierId id, Panier panier, Produit produit, Integer quantite) {
       this.id = id;
       this.panier = panier;
       this.produit = produit;
       this.quantite = quantite;
    }
   
    public LignecommandepanierId getId() {
        return this.id;
    }
    
    public void setId(LignecommandepanierId id) {
        this.id = id;
    }
    public Panier getPanier() {
        return this.panier;
    }
    
    public void setPanier(Panier panier) {
        this.panier = panier;
    }
    public Produit getProduit() {
        return this.produit;
    }
    
    public void setProduit(Produit produit) {
        this.produit = produit;
    }
    public Integer getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(Integer quantite) {
        this.quantite = quantite;
    }




}


