package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1



/**
 * Lignecommandestock generated by hbm2java
 */
public class Lignecommandestock  implements java.io.Serializable {


     private LignecommandestockId id;
     private Commandestock commandestock;
     private Produit produit;
     private Integer quantite;

    public Lignecommandestock() {
    }

	
    public Lignecommandestock(LignecommandestockId id, Commandestock commandestock, Produit produit) {
        this.id = id;
        this.commandestock = commandestock;
        this.produit = produit;
    }
    public Lignecommandestock(LignecommandestockId id, Commandestock commandestock, Produit produit, Integer quantite) {
       this.id = id;
       this.commandestock = commandestock;
       this.produit = produit;
       this.quantite = quantite;
    }
   
    public LignecommandestockId getId() {
        return this.id;
    }
    
    public void setId(LignecommandestockId id) {
        this.id = id;
    }
    public Commandestock getCommandestock() {
        return this.commandestock;
    }
    
    public void setCommandestock(Commandestock commandestock) {
        this.commandestock = commandestock;
    }
    public Produit getProduit() {
        return this.produit;
    }
    
    public void setProduit(Produit produit) {
        this.produit = produit;
    }
    public Integer getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(Integer quantite) {
        this.quantite = quantite;
    }




}


