package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1



/**
 * LignecommandestockId generated by hbm2java
 */
public class LignecommandestockId  implements java.io.Serializable {


     private String codeprod;
     private String format;
     private String designation;
     private String codestock;

    public LignecommandestockId() {
    }

    public LignecommandestockId(String codeprod, String format, String designation, String codestock) {
       this.codeprod = codeprod;
       this.format = format;
       this.designation = designation;
       this.codestock = codestock;
    }
   
    public String getCodeprod() {
        return this.codeprod;
    }
    
    public void setCodeprod(String codeprod) {
        this.codeprod = codeprod;
    }
    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getCodestock() {
        return this.codestock;
    }
    
    public void setCodestock(String codestock) {
        this.codestock = codestock;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LignecommandestockId) ) return false;
		 LignecommandestockId castOther = ( LignecommandestockId ) other; 
         
		 return ( (this.getCodeprod()==castOther.getCodeprod()) || ( this.getCodeprod()!=null && castOther.getCodeprod()!=null && this.getCodeprod().equals(castOther.getCodeprod()) ) )
 && ( (this.getFormat()==castOther.getFormat()) || ( this.getFormat()!=null && castOther.getFormat()!=null && this.getFormat().equals(castOther.getFormat()) ) )
 && ( (this.getDesignation()==castOther.getDesignation()) || ( this.getDesignation()!=null && castOther.getDesignation()!=null && this.getDesignation().equals(castOther.getDesignation()) ) )
 && ( (this.getCodestock()==castOther.getCodestock()) || ( this.getCodestock()!=null && castOther.getCodestock()!=null && this.getCodestock().equals(castOther.getCodestock()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodeprod() == null ? 0 : this.getCodeprod().hashCode() );
         result = 37 * result + ( getFormat() == null ? 0 : this.getFormat().hashCode() );
         result = 37 * result + ( getDesignation() == null ? 0 : this.getDesignation().hashCode() );
         result = 37 * result + ( getCodestock() == null ? 0 : this.getCodestock().hashCode() );
         return result;
   }   


}


