package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1



/**
 * LignedevisId generated by hbm2java
 */
public class LignedevisId  implements java.io.Serializable {


     private String idpersonne;
     private String codefour;
     private String codedevis;

    public LignedevisId() {
    }

    public LignedevisId(String idpersonne, String codefour, String codedevis) {
       this.idpersonne = idpersonne;
       this.codefour = codefour;
       this.codedevis = codedevis;
    }
   
    public String getIdpersonne() {
        return this.idpersonne;
    }
    
    public void setIdpersonne(String idpersonne) {
        this.idpersonne = idpersonne;
    }
    public String getCodefour() {
        return this.codefour;
    }
    
    public void setCodefour(String codefour) {
        this.codefour = codefour;
    }
    public String getCodedevis() {
        return this.codedevis;
    }
    
    public void setCodedevis(String codedevis) {
        this.codedevis = codedevis;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LignedevisId) ) return false;
		 LignedevisId castOther = ( LignedevisId ) other; 
         
		 return ( (this.getIdpersonne()==castOther.getIdpersonne()) || ( this.getIdpersonne()!=null && castOther.getIdpersonne()!=null && this.getIdpersonne().equals(castOther.getIdpersonne()) ) )
 && ( (this.getCodefour()==castOther.getCodefour()) || ( this.getCodefour()!=null && castOther.getCodefour()!=null && this.getCodefour().equals(castOther.getCodefour()) ) )
 && ( (this.getCodedevis()==castOther.getCodedevis()) || ( this.getCodedevis()!=null && castOther.getCodedevis()!=null && this.getCodedevis().equals(castOther.getCodedevis()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdpersonne() == null ? 0 : this.getIdpersonne().hashCode() );
         result = 37 * result + ( getCodefour() == null ? 0 : this.getCodefour().hashCode() );
         result = 37 * result + ( getCodedevis() == null ? 0 : this.getCodedevis().hashCode() );
         return result;
   }   


}


