package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1



/**
 * Lignedevis generated by hbm2java
 */
public class Lignedevis  implements java.io.Serializable {


     private LignedevisId id;
     private Devis devis;
     private Fournisseur fournisseur;
     private Integer prix;

    public Lignedevis() {
    }

	
    public Lignedevis(LignedevisId id, Devis devis, Fournisseur fournisseur) {
        this.id = id;
        this.devis = devis;
        this.fournisseur = fournisseur;
    }
    public Lignedevis(LignedevisId id, Devis devis, Fournisseur fournisseur, Integer prix) {
       this.id = id;
       this.devis = devis;
       this.fournisseur = fournisseur;
       this.prix = prix;
    }
   
    public LignedevisId getId() {
        return this.id;
    }
    
    public void setId(LignedevisId id) {
        this.id = id;
    }
    public Devis getDevis() {
        return this.devis;
    }
    
    public void setDevis(Devis devis) {
        this.devis = devis;
    }
    public Fournisseur getFournisseur() {
        return this.fournisseur;
    }
    
    public void setFournisseur(Fournisseur fournisseur) {
        this.fournisseur = fournisseur;
    }
    public Integer getPrix() {
        return this.prix;
    }
    
    public void setPrix(Integer prix) {
        this.prix = prix;
    }




}


