package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1



/**
 * LivreurId generated by hbm2java
 */
public class LivreurId  implements java.io.Serializable {


     private String idpersonne;
     private String type;
     private String codelivreur;

    public LivreurId() {
    }

    public LivreurId(String idpersonne, String type, String codelivreur) {
       this.idpersonne = idpersonne;
       this.type = type;
       this.codelivreur = codelivreur;
    }
   
    public String getIdpersonne() {
        return this.idpersonne;
    }
    
    public void setIdpersonne(String idpersonne) {
        this.idpersonne = idpersonne;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getCodelivreur() {
        return this.codelivreur;
    }
    
    public void setCodelivreur(String codelivreur) {
        this.codelivreur = codelivreur;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LivreurId) ) return false;
		 LivreurId castOther = ( LivreurId ) other; 
         
		 return ( (this.getIdpersonne()==castOther.getIdpersonne()) || ( this.getIdpersonne()!=null && castOther.getIdpersonne()!=null && this.getIdpersonne().equals(castOther.getIdpersonne()) ) )
 && ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
 && ( (this.getCodelivreur()==castOther.getCodelivreur()) || ( this.getCodelivreur()!=null && castOther.getCodelivreur()!=null && this.getCodelivreur().equals(castOther.getCodelivreur()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdpersonne() == null ? 0 : this.getIdpersonne().hashCode() );
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         result = 37 * result + ( getCodelivreur() == null ? 0 : this.getCodelivreur().hashCode() );
         return result;
   }   


}


