package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Livraison generated by hbm2java
 */
public class Livraison  implements java.io.Serializable {


     private String codelivraison;
     private Livreur livreur;
     private String datelivraison;
     private Integer fraislivraison;
     private Set commandeclients = new HashSet(0);

    public Livraison() {
    }

	
    public Livraison(String codelivraison) {
        this.codelivraison = codelivraison;
    }
    public Livraison(String codelivraison, Livreur livreur, String datelivraison, Integer fraislivraison, Set commandeclients) {
       this.codelivraison = codelivraison;
       this.livreur = livreur;
       this.datelivraison = datelivraison;
       this.fraislivraison = fraislivraison;
       this.commandeclients = commandeclients;
    }
   
    public String getCodelivraison() {
        return this.codelivraison;
    }
    
    public void setCodelivraison(String codelivraison) {
        this.codelivraison = codelivraison;
    }
    public Livreur getLivreur() {
        return this.livreur;
    }
    
    public void setLivreur(Livreur livreur) {
        this.livreur = livreur;
    }
    public String getDatelivraison() {
        return this.datelivraison;
    }
    
    public void setDatelivraison(String datelivraison) {
        this.datelivraison = datelivraison;
    }
    public Integer getFraislivraison() {
        return this.fraislivraison;
    }
    
    public void setFraislivraison(Integer fraislivraison) {
        this.fraislivraison = fraislivraison;
    }
    public Set getCommandeclients() {
        return this.commandeclients;
    }
    
    public void setCommandeclients(Set commandeclients) {
        this.commandeclients = commandeclients;
    }




}


