package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Panier generated by hbm2java
 */
public class Panier  implements java.io.Serializable {


     private String codepanier;
     private Client client;
     private Integer montant;
     private Integer nombrearticle;
     private String etat;
     private String datepanier;
     private Set commandeclients = new HashSet(0);
     private Set lignecommandepaniers = new HashSet(0);

    public Panier() {
    }

	
    public Panier(String codepanier) {
        this.codepanier = codepanier;
    }
    public Panier(String codepanier, Client client, Integer montant, Integer nombrearticle, String etat, String datepanier, Set commandeclients, Set lignecommandepaniers) {
       this.codepanier = codepanier;
       this.client = client;
       this.montant = montant;
       this.nombrearticle = nombrearticle;
       this.etat = etat;
       this.datepanier = datepanier;
       this.commandeclients = commandeclients;
       this.lignecommandepaniers = lignecommandepaniers;
    }
   
    public String getCodepanier() {
        return this.codepanier;
    }
    
    public void setCodepanier(String codepanier) {
        this.codepanier = codepanier;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Integer getMontant() {
        return this.montant;
    }
    
    public void setMontant(Integer montant) {
        this.montant = montant;
    }
    public Integer getNombrearticle() {
        return this.nombrearticle;
    }
    
    public void setNombrearticle(Integer nombrearticle) {
        this.nombrearticle = nombrearticle;
    }
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }
    public String getDatepanier() {
        return this.datepanier;
    }
    
    public void setDatepanier(String datepanier) {
        this.datepanier = datepanier;
    }
    public Set getCommandeclients() {
        return this.commandeclients;
    }
    
    public void setCommandeclients(Set commandeclients) {
        this.commandeclients = commandeclients;
    }
    public Set getLignecommandepaniers() {
        return this.lignecommandepaniers;
    }
    
    public void setLignecommandepaniers(Set lignecommandepaniers) {
        this.lignecommandepaniers = lignecommandepaniers;
    }




}


