package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Personne generated by hbm2java
 */
public class Personne  implements java.io.Serializable {


     private String idpersonne;
     private String prenom;
     private String nom;
     private String datenaiss;
     private String lieunaiss;
     private String adresse;
     private String telephone;
     private String email;
     private String categorie;
     private String nationalite;
     private String sexe;
     private String login;
     private String motpasse;
     private String photo;
     private String dateinscrip;
     private Set privileges = new HashSet(0);
     private Set clients = new HashSet(0);
     private Set detailsmessages = new HashSet(0);
     private Set employes = new HashSet(0);
     private Set administrateurs = new HashSet(0);
     private Set fournisseurs = new HashSet(0);

    public Personne() {
    }

	
    public Personne(String idpersonne) {
        this.idpersonne = idpersonne;
    }
    public Personne(String idpersonne, String prenom, String nom, String datenaiss, String lieunaiss, String adresse, String telephone, String email, String categorie, String nationalite, String sexe, String login, String motpasse, String photo, String dateinscrip, Set privileges, Set clients, Set detailsmessages, Set employes, Set administrateurs, Set fournisseurs) {
       this.idpersonne = idpersonne;
       this.prenom = prenom;
       this.nom = nom;
       this.datenaiss = datenaiss;
       this.lieunaiss = lieunaiss;
       this.adresse = adresse;
       this.telephone = telephone;
       this.email = email;
       this.categorie = categorie;
       this.nationalite = nationalite;
       this.sexe = sexe;
       this.login = login;
       this.motpasse = motpasse;
       this.photo = photo;
       this.dateinscrip = dateinscrip;
       this.privileges = privileges;
       this.clients = clients;
       this.detailsmessages = detailsmessages;
       this.employes = employes;
       this.administrateurs = administrateurs;
       this.fournisseurs = fournisseurs;
    }
   
    public String getIdpersonne() {
        return this.idpersonne;
    }
    
    public void setIdpersonne(String idpersonne) {
        this.idpersonne = idpersonne;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDatenaiss() {
        return this.datenaiss;
    }
    
    public void setDatenaiss(String datenaiss) {
        this.datenaiss = datenaiss;
    }
    public String getLieunaiss() {
        return this.lieunaiss;
    }
    
    public void setLieunaiss(String lieunaiss) {
        this.lieunaiss = lieunaiss;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCategorie() {
        return this.categorie;
    }
    
    public void setCategorie(String categorie) {
        this.categorie = categorie;
    }
    public String getNationalite() {
        return this.nationalite;
    }
    
    public void setNationalite(String nationalite) {
        this.nationalite = nationalite;
    }
    public String getSexe() {
        return this.sexe;
    }
    
    public void setSexe(String sexe) {
        this.sexe = sexe;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getMotpasse() {
        return this.motpasse;
    }
    
    public void setMotpasse(String motpasse) {
        this.motpasse = motpasse;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getDateinscrip() {
        return this.dateinscrip;
    }
    
    public void setDateinscrip(String dateinscrip) {
        this.dateinscrip = dateinscrip;
    }
    public Set getPrivileges() {
        return this.privileges;
    }
    
    public void setPrivileges(Set privileges) {
        this.privileges = privileges;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }
    public Set getDetailsmessages() {
        return this.detailsmessages;
    }
    
    public void setDetailsmessages(Set detailsmessages) {
        this.detailsmessages = detailsmessages;
    }
    public Set getEmployes() {
        return this.employes;
    }
    
    public void setEmployes(Set employes) {
        this.employes = employes;
    }
    public Set getAdministrateurs() {
        return this.administrateurs;
    }
    
    public void setAdministrateurs(Set administrateurs) {
        this.administrateurs = administrateurs;
    }
    public Set getFournisseurs() {
        return this.fournisseurs;
    }
    
    public void setFournisseurs(Set fournisseurs) {
        this.fournisseurs = fournisseurs;
    }




}


