package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Privilege generated by hbm2java
 */
public class Privilege  implements java.io.Serializable {


     private String idpriv;
     private String intitule;
     private String datedebut;
     private String datefin;
     private Integer illimite;
     private Set personnes = new HashSet(0);

    public Privilege() {
    }

	
    public Privilege(String idpriv) {
        this.idpriv = idpriv;
    }
    public Privilege(String idpriv, String intitule, String datedebut, String datefin, Integer illimite, Set personnes) {
       this.idpriv = idpriv;
       this.intitule = intitule;
       this.datedebut = datedebut;
       this.datefin = datefin;
       this.illimite = illimite;
       this.personnes = personnes;
    }
   
    public String getIdpriv() {
        return this.idpriv;
    }
    
    public void setIdpriv(String idpriv) {
        this.idpriv = idpriv;
    }
    public String getIntitule() {
        return this.intitule;
    }
    
    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }
    public String getDatedebut() {
        return this.datedebut;
    }
    
    public void setDatedebut(String datedebut) {
        this.datedebut = datedebut;
    }
    public String getDatefin() {
        return this.datefin;
    }
    
    public void setDatefin(String datefin) {
        this.datefin = datefin;
    }
    public Integer getIllimite() {
        return this.illimite;
    }
    
    public void setIllimite(Integer illimite) {
        this.illimite = illimite;
    }
    public Set getPersonnes() {
        return this.personnes;
    }
    
    public void setPersonnes(Set personnes) {
        this.personnes = personnes;
    }




}


