package gestion.trelux.metier;
// Generated 9 juin 2018 15:16:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Produit generated by hbm2java
 */
public class Produit  implements java.io.Serializable {


     private ProduitId id;
     private Familleboisson familleboisson;
     private String datereception;
     private String dateperemtion;
     private Integer prixunitaire;
     private String photo;
     private Integer quantiteenstock;
     private Integer seuilminimum;
     private Integer prixachat;
     private Integer prixvente;
     private Set conditionnements = new HashSet(0);
     private Set lignecommandestocks = new HashSet(0);
     private Set lignecommandepaniers = new HashSet(0);

    public Produit() {
    }

	
    public Produit(ProduitId id) {
        this.id = id;
    }
    public Produit(ProduitId id, Familleboisson familleboisson, String datereception, String dateperemtion, Integer prixunitaire, String photo, Integer quantiteenstock, Integer seuilminimum, Integer prixachat, Integer prixvente, Set conditionnements, Set lignecommandestocks, Set lignecommandepaniers) {
       this.id = id;
       this.familleboisson = familleboisson;
       this.datereception = datereception;
       this.dateperemtion = dateperemtion;
       this.prixunitaire = prixunitaire;
       this.photo = photo;
       this.quantiteenstock = quantiteenstock;
       this.seuilminimum = seuilminimum;
       this.prixachat = prixachat;
       this.prixvente = prixvente;
       this.conditionnements = conditionnements;
       this.lignecommandestocks = lignecommandestocks;
       this.lignecommandepaniers = lignecommandepaniers;
    }
   
    public ProduitId getId() {
        return this.id;
    }
    
    public void setId(ProduitId id) {
        this.id = id;
    }
    public Familleboisson getFamilleboisson() {
        return this.familleboisson;
    }
    
    public void setFamilleboisson(Familleboisson familleboisson) {
        this.familleboisson = familleboisson;
    }
    public String getDatereception() {
        return this.datereception;
    }
    
    public void setDatereception(String datereception) {
        this.datereception = datereception;
    }
    public String getDateperemtion() {
        return this.dateperemtion;
    }
    
    public void setDateperemtion(String dateperemtion) {
        this.dateperemtion = dateperemtion;
    }
    public Integer getPrixunitaire() {
        return this.prixunitaire;
    }
    
    public void setPrixunitaire(Integer prixunitaire) {
        this.prixunitaire = prixunitaire;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public Integer getQuantiteenstock() {
        return this.quantiteenstock;
    }
    
    public void setQuantiteenstock(Integer quantiteenstock) {
        this.quantiteenstock = quantiteenstock;
    }
    public Integer getSeuilminimum() {
        return this.seuilminimum;
    }
    
    public void setSeuilminimum(Integer seuilminimum) {
        this.seuilminimum = seuilminimum;
    }
    public Integer getPrixachat() {
        return this.prixachat;
    }
    
    public void setPrixachat(Integer prixachat) {
        this.prixachat = prixachat;
    }
    public Integer getPrixvente() {
        return this.prixvente;
    }
    
    public void setPrixvente(Integer prixvente) {
        this.prixvente = prixvente;
    }
    public Set getConditionnements() {
        return this.conditionnements;
    }
    
    public void setConditionnements(Set conditionnements) {
        this.conditionnements = conditionnements;
    }
    public Set getLignecommandestocks() {
        return this.lignecommandestocks;
    }
    
    public void setLignecommandestocks(Set lignecommandestocks) {
        this.lignecommandestocks = lignecommandestocks;
    }
    public Set getLignecommandepaniers() {
        return this.lignecommandepaniers;
    }
    
    public void setLignecommandepaniers(Set lignecommandepaniers) {
        this.lignecommandepaniers = lignecommandepaniers;
    }




}


